spring:
  application:
    name: config-client                     #指定了配置文件的应用名
  cloud:
    config:
      uri: http://localhost:8888/        #Config server的uri
      profile: development                       #指定的环境
      label: master                      #指定分支
#management:
#  security:
#    enabled: false

#spring.application.name=config-client
#spring.profiles.active=development
#spring.cloud.config.uri=http://localhost:8888
