server:
  port: 8090

spring:
  application:
    name: cloud-simple-service

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://172.16.7.40:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
